/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UptimeRouteImport } from './routes/uptime'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as DashboardUptimeRouteImport } from './routes/dashboard/uptime'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardServersRouteImport } from './routes/dashboard/servers'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUptimeRouteImport } from './routes/admin/uptime'
import { Route as AdminPterodactylRouteImport } from './routes/admin/pterodactyl'
import { Route as AdminPlansRouteImport } from './routes/admin/plans'
import { Route as AdminExtraApisRouteImport } from './routes/admin/extra-apis'
import { Route as ApiPublicHooksUptimeCheckRouteImport } from './routes/api/public/hooks/uptime-check'
import { Route as ApiPublicHooksAutoSuspendRouteImport } from './routes/api/public/hooks/auto-suspend'

const UptimeRoute = UptimeRouteImport.update({
  id: '/uptime',
  path: '/uptime',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardUptimeRoute = DashboardUptimeRouteImport.update({
  id: '/dashboard/uptime',
  path: '/dashboard/uptime',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServersRoute = DashboardServersRouteImport.update({
  id: '/dashboard/servers',
  path: '/dashboard/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUptimeRoute = AdminUptimeRouteImport.update({
  id: '/admin/uptime',
  path: '/admin/uptime',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPterodactylRoute = AdminPterodactylRouteImport.update({
  id: '/admin/pterodactyl',
  path: '/admin/pterodactyl',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExtraApisRoute = AdminExtraApisRouteImport.update({
  id: '/admin/extra-apis',
  path: '/admin/extra-apis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksUptimeCheckRoute =
  ApiPublicHooksUptimeCheckRouteImport.update({
    id: '/api/public/hooks/uptime-check',
    path: '/api/public/hooks/uptime-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoSuspendRoute =
  ApiPublicHooksAutoSuspendRouteImport.update({
    id: '/api/public/hooks/auto-suspend',
    path: '/api/public/hooks/auto-suspend',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/docs': typeof DocsRouteWithChildren
  '/plans': typeof PlansRoute
  '/uptime': typeof UptimeRoute
  '/admin/extra-apis': typeof AdminExtraApisRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/pterodactyl': typeof AdminPterodactylRoute
  '/admin/uptime': typeof AdminUptimeRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/servers': typeof DashboardServersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/uptime': typeof DashboardUptimeRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/hooks/auto-suspend': typeof ApiPublicHooksAutoSuspendRoute
  '/api/public/hooks/uptime-check': typeof ApiPublicHooksUptimeCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/docs': typeof DocsRouteWithChildren
  '/plans': typeof PlansRoute
  '/uptime': typeof UptimeRoute
  '/admin/extra-apis': typeof AdminExtraApisRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/pterodactyl': typeof AdminPterodactylRoute
  '/admin/uptime': typeof AdminUptimeRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/servers': typeof DashboardServersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/uptime': typeof DashboardUptimeRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/hooks/auto-suspend': typeof ApiPublicHooksAutoSuspendRoute
  '/api/public/hooks/uptime-check': typeof ApiPublicHooksUptimeCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/docs': typeof DocsRouteWithChildren
  '/plans': typeof PlansRoute
  '/uptime': typeof UptimeRoute
  '/admin/extra-apis': typeof AdminExtraApisRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/pterodactyl': typeof AdminPterodactylRoute
  '/admin/uptime': typeof AdminUptimeRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/servers': typeof DashboardServersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/uptime': typeof DashboardUptimeRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/hooks/auto-suspend': typeof ApiPublicHooksAutoSuspendRoute
  '/api/public/hooks/uptime-check': typeof ApiPublicHooksUptimeCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/docs'
    | '/plans'
    | '/uptime'
    | '/admin/extra-apis'
    | '/admin/plans'
    | '/admin/pterodactyl'
    | '/admin/uptime'
    | '/admin/users'
    | '/dashboard/servers'
    | '/dashboard/settings'
    | '/dashboard/uptime'
    | '/docs/$slug'
    | '/dashboard/'
    | '/api/public/hooks/auto-suspend'
    | '/api/public/hooks/uptime-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/docs'
    | '/plans'
    | '/uptime'
    | '/admin/extra-apis'
    | '/admin/plans'
    | '/admin/pterodactyl'
    | '/admin/uptime'
    | '/admin/users'
    | '/dashboard/servers'
    | '/dashboard/settings'
    | '/dashboard/uptime'
    | '/docs/$slug'
    | '/dashboard'
    | '/api/public/hooks/auto-suspend'
    | '/api/public/hooks/uptime-check'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/docs'
    | '/plans'
    | '/uptime'
    | '/admin/extra-apis'
    | '/admin/plans'
    | '/admin/pterodactyl'
    | '/admin/uptime'
    | '/admin/users'
    | '/dashboard/servers'
    | '/dashboard/settings'
    | '/dashboard/uptime'
    | '/docs/$slug'
    | '/dashboard/'
    | '/api/public/hooks/auto-suspend'
    | '/api/public/hooks/uptime-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  DocsRoute: typeof DocsRouteWithChildren
  PlansRoute: typeof PlansRoute
  UptimeRoute: typeof UptimeRoute
  AdminExtraApisRoute: typeof AdminExtraApisRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminPterodactylRoute: typeof AdminPterodactylRoute
  AdminUptimeRoute: typeof AdminUptimeRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DashboardServersRoute: typeof DashboardServersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUptimeRoute: typeof DashboardUptimeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiPublicHooksAutoSuspendRoute: typeof ApiPublicHooksAutoSuspendRoute
  ApiPublicHooksUptimeCheckRoute: typeof ApiPublicHooksUptimeCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uptime': {
      id: '/uptime'
      path: '/uptime'
      fullPath: '/uptime'
      preLoaderRoute: typeof UptimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/uptime': {
      id: '/dashboard/uptime'
      path: '/dashboard/uptime'
      fullPath: '/dashboard/uptime'
      preLoaderRoute: typeof DashboardUptimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/servers': {
      id: '/dashboard/servers'
      path: '/dashboard/servers'
      fullPath: '/dashboard/servers'
      preLoaderRoute: typeof DashboardServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/uptime': {
      id: '/admin/uptime'
      path: '/admin/uptime'
      fullPath: '/admin/uptime'
      preLoaderRoute: typeof AdminUptimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pterodactyl': {
      id: '/admin/pterodactyl'
      path: '/admin/pterodactyl'
      fullPath: '/admin/pterodactyl'
      preLoaderRoute: typeof AdminPterodactylRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/extra-apis': {
      id: '/admin/extra-apis'
      path: '/admin/extra-apis'
      fullPath: '/admin/extra-apis'
      preLoaderRoute: typeof AdminExtraApisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/uptime-check': {
      id: '/api/public/hooks/uptime-check'
      path: '/api/public/hooks/uptime-check'
      fullPath: '/api/public/hooks/uptime-check'
      preLoaderRoute: typeof ApiPublicHooksUptimeCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-suspend': {
      id: '/api/public/hooks/auto-suspend'
      path: '/api/public/hooks/auto-suspend'
      fullPath: '/api/public/hooks/auto-suspend'
      preLoaderRoute: typeof ApiPublicHooksAutoSuspendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  DocsRoute: DocsRouteWithChildren,
  PlansRoute: PlansRoute,
  UptimeRoute: UptimeRoute,
  AdminExtraApisRoute: AdminExtraApisRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminPterodactylRoute: AdminPterodactylRoute,
  AdminUptimeRoute: AdminUptimeRoute,
  AdminUsersRoute: AdminUsersRoute,
  DashboardServersRoute: DashboardServersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUptimeRoute: DashboardUptimeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiPublicHooksAutoSuspendRoute: ApiPublicHooksAutoSuspendRoute,
  ApiPublicHooksUptimeCheckRoute: ApiPublicHooksUptimeCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
